ami_id = "ami-0169776ce0edf5fc5"  # This AMI is for us-east; replace it with your region's Marketplace AMI ID.
aws_region           = "us-east-1"
aws_availability_zone = "us-east-1a"
vpc_name             = "relianoid-vpc"
subnet_name          = "relianoid-subnet"
vm_name              = "relianoid-vm"
instance_type        = "t3.medium"
key_name             = "relianoid-key"
public_ssh_key_path  = "id_rsa.pub"
